#!/usr/bin/env python
"""This file is automatically generated by generate_version_info
It uses the current working tree to determine the revision.
So don't edit it. :)
"""

version_info = {'branch_nick': u'pyzim-trunk',
 'build_date': '2010-01-10 22:58:20 +0100',
 'clean': None,
 'date': '2010-01-10 22:47:31 +0100',
 'revision_id': 'pardus@cpan.org-20100110214731-fy60hrbzq67ygukm',
 'revno': 180}

revisions = {}

file_revisions = {}



if __name__ == '__main__':
    print 'revision: %(revno)d' % version_info
    print 'nick: %(branch_nick)s' % version_info
    print 'revision id: %(revision_id)s' % version_info
