# built-in slideshow configuration
#
# override settings in:
#  ~/.slideshow/slideshow.yml
# or
#  ./slideshow.yml or ./.slideshow.yml

#lets you define default/fallback headers

headers:
  generator: <%= Slideshow.generator %> 
  author:  Your Name Here
  email:   Your Email Here
  company: Your Company Here
  title:   Your Title Here
  subtitle: Your Subtitle Here
  footer: Your Footer Here
  subfooter: Your Subfooter Here 
  date:  <%= Date.today %>

  # todo: use nested config?? eg.
  # gradient:
  #   theme: dark
  #   color1:
  gradient-theme:  dark
  gradient-color1:  red
  gradient-color2:  black

  # todo: use nested config??
  #
  # ultraviolet (uv) | coderay (cr) 
  code-engine:  uv
  # Text Mate Hyperlink for Source?
  code-txmt:  false
  # todo: add code-linenumbers??



# shortcuts for fetching template packs
#   map shortcut to URI
    
fetch:
    s6syntax: https://github.com/geraldb/slideshow-s6-syntax-highlighter/raw/master/s6syntax.txt
    s6blank: https://github.com/geraldb/slideshow-s6-blank/raw/master/s6blank.txt
    s5blank: https://github.com/geraldb/slideshow-s5-blank/raw/master/s5blank.txt
    s5themes: https://github.com/geraldb/slideshow-s5-themes/raw/master/s5themes.txt
    fullerscreen: https://github.com/geraldb/slideshow-fullerscreen/raw/master/fullerscreen.txt
    slidy: https://github.com/geraldb/slideshow-slidy/raw/master/slidy.txt
    g5: https://github.com/geraldb/slideshow-google-html5-slides/raw/master/g5.txt
    slippy: https://github.com/geraldb/slideshow-slippy/raw/master/slippy.txt
    csss: https://github.com/geraldb/slideshow-csss/raw/master/csss.txt
    deck.js: https://github.com/geraldb/slideshow-deck.js/raw/master/deck.js.txt
    impress.js: https://github.com/geraldb/slideshow-impress.js/raw/master/impress.js.txt
    shower: https://github.com/geraldb/slideshow-shower/raw/master/shower.txt

# your google analytics code  
analytics:
    google: UA-XXX
    

helper:
  renames: []
  exprs: []

### markup (textile, markdown) config

# filters to run before markup processing
filters: []
    
textile:
  extnames: []  
  
markdown:
  extnames: []
  libs:     []
  